# NumPy Exercises 


#### Import NumPy as np

In [115]:
import numpy as np

#### Print Numpy version

In [114]:
print(np.__version__)

1.25.2


#### Create an array of 10 zeros 

In [8]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [10]:
array_once = np.ones(10)
print(array_once)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [15]:
arr_fives = np.ones(10) * 5
print(arr_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [20]:
arr_integers = np.arange(10, 51)
print(arr_integers)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [22]:
arr_integers = np.arange(10,51,2)
print(arr_integers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [28]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [38]:
random_num = np.random.rand()
print(random_num)

0.4461782576640325


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [39]:
random_num = np.random.rand(25)
print(random_num)

[0.24467077 0.73379777 0.25095017 0.93373794 0.37447492 0.47959331
 0.63366441 0.60315434 0.95726195 0.14618235 0.41548577 0.70596225
 0.82389261 0.27339596 0.05204148 0.35444923 0.0190379  0.19952814
 0.28345618 0.07555992 0.66024939 0.04515792 0.10083872 0.10317699
 0.92927475]


#### Create the following matrix:

In [54]:
matrix = np.arange(0.1, 2.1, 0.1).reshape(4, 5)

print(matrix)


[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [58]:
result_array = np.linspace(0, 1, 20).reshape(4, 5)

print(result_array)

[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]
 [0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [60]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [97]:
result_matrix = np.arange(12, 26).reshape(2, 7)

print(result_matrix)

[[12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [95]:
print(mat[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [100]:
result_matrix = np.array([[2], [7], [12]])

# Print the resulting matrix
print(result_matrix)

[[ 2]
 [ 7]
 [12]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [101]:
result_array = np.arange(21, 26)

print(result_array)

[21 22 23 24 25]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [102]:
result_array = np.arange(16, 26)

print(result_array)

[16 17 18 19 20 21 22 23 24 25]


### Now do the following

#### Get the sum of all the values in mat

In [104]:
sum_of_values = np.sum(mat)
print(sum_of_values)

325


#### Get the standard deviation of the values in mat

In [106]:
std_deviation = np.std(mat)
print(std_deviation)

7.211102550927978


#### Get the sum of all the columns in mat

In [108]:
sum_of_columns = np.sum(mat, axis=0)
print(sum_of_columns)

[55 60 65 70 75]
